[Block(BlockID.andesite)]
[Block(BlockID.blackstone)]
[Block(BlockID.amethyst_block)]
[Block(BlockID.amethyst_cluster)]
[Block(BlockID.small_amethyst_bud)]
[Block(BlockID.medium_amethyst_bud)]
[Block(BlockID.large_amethyst_bud)]
[Block(BlockID.budding_amethyst)]
[Block(BlockID.dripstone_block)]
[Block(BlockID.pointed_dripstone)]
[Block(BlockID.polished_blackstone_bricks)]
[Block(BlockID.gilded_blackstone)]
[Block(BlockID.brain_coral_block)]
[Block(BlockID.bubble_coral_block)]
[Block(BlockID.dead_brain_coral_block)]
[Block(BlockID.dead_bubble_coral_block)]
[Block(BlockID.dead_fire_coral_block)]
[Block(BlockID.dead_horn_coral_block)]
[Block(BlockID.dead_tube_coral_block)]
[Block(BlockID.fire_coral_block)]
[Block(BlockID.horn_coral_block)]
[Block(BlockID.tube_coral_block)]
[Block(BlockID.bookshelf)]
[Block(BlockID.dark_prismarine)]
[Block(BlockID.diorite)]
[Block(BlockID.granite)]
[Block(BlockID.piston)]
[Block(BlockID.prismarine)]
[Block(BlockID.prismarine_bricks)]
public class BlockWithHardness_1_5 : IWorldBlock
{
    public float hardness => 1.5f;
    public bool hasCollision => true;
}
