[Block(DefaultBlockState.andesite)]
[Block(DefaultBlockState.blackstone)]
[Block(DefaultBlockState.amethyst_block)]
[Block(DefaultBlockState.amethyst_cluster)]
[Block(DefaultBlockState.small_amethyst_bud)]
[Block(DefaultBlockState.medium_amethyst_bud)]
[Block(DefaultBlockState.large_amethyst_bud)]
[Block(DefaultBlockState.budding_amethyst)]
[Block(DefaultBlockState.dripstone_block)]
[Block(DefaultBlockState.pointed_dripstone)]
[Block(DefaultBlockState.polished_blackstone_bricks)]
[Block(DefaultBlockState.gilded_blackstone)]
[Block(DefaultBlockState.brain_coral_block)]
[Block(DefaultBlockState.bubble_coral_block)]
[Block(DefaultBlockState.dead_brain_coral_block)]
[Block(DefaultBlockState.dead_bubble_coral_block)]
[Block(DefaultBlockState.dead_fire_coral_block)]
[Block(DefaultBlockState.dead_horn_coral_block)]
[Block(DefaultBlockState.dead_tube_coral_block)]
[Block(DefaultBlockState.fire_coral_block)]
[Block(DefaultBlockState.horn_coral_block)]
[Block(DefaultBlockState.tube_coral_block)]
[Block(DefaultBlockState.bookshelf)]
[Block(DefaultBlockState.dark_prismarine)]
[Block(DefaultBlockState.diorite)]
[Block(DefaultBlockState.granite)]
[Block(DefaultBlockState.piston)]
[Block(DefaultBlockState.prismarine)]
[Block(DefaultBlockState.prismarine_bricks)]
public class BlockWithHardness_1_5 : IWorldBlock
{
    public float hardness => 1.5f;
    public bool hasCollision => true;
}
